version: '3.3'

services:

  verificationserver:
    container_name: verificationserver
    image: wooyay/cwa-verification-server:latest
    ports:
      - "8082:8080"
     
  iam:
    container_name: iam
    image: wooyay/cwa-verification-iam:latest
    environment:   
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin     
      KEYCLOAK_IMPORT: /tmp/cwa-realm.json
      SSL_KEY_STORE: /opt/jboss/keycloak/standalone/configuration/ONLY_FOR_TEST_keystore.jks
      SSL_KEY_STORE_PASSWORD: secret
    volumes:
      - "./cwa-realm.json:/tmp/cwa-realm.json"
      - "./cwa-verification-iam/src/themes/cwa:/opt/jboss/keycloak/themes/cwa"
    ports:
      - "8080:8080"
      - "8443:8443"
      
  verificationportal:
    container_name: verificationportal
    image: wooyay/cwa-verification-portal:latest    
    ports:
      - "8081:8081"
    entrypoint: "java -Dkeycloak.auth-server-url=http://iam:8080/auth -Dcwa-verification-server.url=http://verificationserver:8080 -jar app.jar"
    
  testresultserver:
    container_name: testresultserver
    image: wooyay/cwa-testresult-server:latest
    ports:
      - "8083:8080"